name: Release

on:
  release:
    types: [ published ]

permissions:
  id-token: write
  contents: read

jobs:

  npmjs:
    name: npmjs.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm config set git-tag-version=false
      - run: npm version ${{ github.event.release.tag_name }}
      - run: npm publish
